services:
  app:
    container_name: unidev-fe-core-dev
    image: unidev-fe-core-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "10002:3000"
    volumes:
      - ./src:/src
      - ./package.json:/src/package.json
      - ./src/node_modules:/src/node_modules
    environment:
      - HOST=0.0.0.0
