services:
  app:
    container_name: unidev-fe-core
    image: unidev-fe-core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10002:3000
    volumes:
      - ./src:/src
      - ./package.json:/src/package.json:ro
      - /src/node_modules
    environment:
      - HOST=0.0.0.0
    restart: always
