services:
  app:
    container_name: unidev-fe-core
    image: unidev-fe-core
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 10002:3000
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - HOST=0.0.0.0
    restart: always
